### ISSUE TITLE
内置 SS 支持 chacha20

### ISSUE THREAD

**Issue by gsgqgyq** [mithril-global/GoAgentX#1]
既然内置插件都更新了，大大顺道加个shadowsocks chacha20 的支持吧。

**Comment by mithril-asia** [comment]
问题是作者把加密方式列表写到程序里了。。。如果真的需要的话可以勾选“高级设置》使用自定义配置模版”，然后把加密方式那里改成chacha20就好了

**Comment by mithril-asia** [comment]
如果你有可用的 Mac 开发者证书也可以，我试着修改了gxbundle，然而他有签名检测，改了之后加载不了了

**Comment by mithril-asia** [comment]
调试好了，下载现在的`master`分支看看～

**Comment by gsgqgyq** [comment]
嗯，有了！ thanks~

**Comment by mithril-asia** [comment]
OK~
