### ISSUE TITLE
更新了哪些方面呢？

### ISSUE THREAD

**Issue by darkr4y** [mithril-global/GoAgentX#2]
只是更新了依赖库？

**Comment by mithril-asia** [comment]
更新了ss版本，加入了新的加密模式

**Comment by darkr4y** [comment]
为何只发布bin呢？源码呢…

**Comment by mithril-asia** [comment]
因为这个没有源码啊，源码原作者在ss作者被水表的时候就没更新了，找遍全网都没有。现在这个是我直接改bin的。。。

**Comment by darkr4y** [comment]
以后更新依赖库时，直接替换ss即可？

**Comment by mithril-asia** [comment]
README 里写了步骤。需要改链接。

**Comment by maboloshi** [comment]
我说怎么 软件界面里的ss 版本没变了 原来是"硬改"的
哎 原作者直接将原项目删除了 不知道谁还保留最后一次的源代码 分享上来
1.0.2版本的源代码 git上还有其他人保留的

**Comment by mithril-asia** [comment]
@maboloshi 如果你愿意可以试着联系作者看看能不能私下放出来吧，1.0.2这个太老了。

**Comment by maboloshi** [comment]
建议顺便更新一下插件版本号么
Contents/PlugIns/XXXXXX.gxbundle/Contents/Info.plist

这里讲了其他插件的更新方法
https://www.logcg.com/archives/1296.html

**Comment by mithril-asia** [comment]
我看看。顺便链接死了

**Comment by mithril-asia** [comment]
COW is updated for High Sierra update.
