### ISSUE TITLE
希望更新Shadowsock-Rss

### ISSUE THREAD

**Issue by kokokobe** [mithril-global/GoAgentX#4]
希望更新Shadowsock-Rss 的内容
https://github.com/breakwa11/shadowsocks-rss

**Comment by ProfFan** [comment]
这是C#的

**Comment by mithril-asia** [comment]
这是Windows上面的？

**Comment by maboloshi** [comment]
这里有他打包的插件
https://bit.no.com:43110/shadowsocksr.bit/?

只是不知为啥 安装后 添加设置的下拉菜单中显示不了

![snip20161005_1](https://cloud.githubusercontent.com/assets/7850715/19112134/daa06bd4-8b35-11e6-9a6c-8e1da26c9731.png)
![snip20161005_2](https://cloud.githubusercontent.com/assets/7850715/19112135/daa5f5ae-8b35-11e6-96c1-fb54fa57e461.png)

**Comment by mithril-asia** [comment]
ShadowsocksR is considered insecure for many reasons. Will now close.

**Comment by mithril-asia** [comment]
Now implemented with a separate plugin due to large user demand. Plus you can add by using the "+" button.

**Comment by hadifarnoud** [comment]
how does it work @mithril-asia ?
