### ISSUE TITLE
请问这个到底怎么用啊

### ISSUE THREAD

**Issue by dreamchaser123** [mithril-global/GoAgentX#8]
小白求教，搞了半天不会设置
<img width="712" alt="screen shot 0030-01-26 at 10 59 26 am" src="https://user-images.githubusercontent.com/26835325/35423294-0bbd8e7a-0288-11e8-8bf9-bde614d7db8e.png">

**Comment by mithril-asia** [comment]
點擊+號添加一個ShadowSocks代理

**Comment by dreamchaser123** [comment]
@mithril-asia 可是我并没有ss的账号，而且其他代理不行么？

**Comment by mithril-asia** [comment]
Please name your requests more thoroughly.

**Comment by dreamchaser123** [comment]
@mithril-asia Well, I don't have a ShadowSocks account, neither could I fill in those blanks.
<img width="712" alt="screen shot 2018-01-31 at 16 35 03" src="https://user-images.githubusercontent.com/26835325/35612722-bfec100e-06a4-11e8-9473-939e15506b12.png">

**Comment by mithril-asia** [comment]
Not relevant.
